# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ProveYourself

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://provendbdev.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_426dc373dde84225af931a2ced427bff }}
        password: ${{ secrets.AzureAppService_ContainerPassword_396e6930e6df4de7ad2c603b8287f5ca }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: provendbdev.azurecr.io/proveyourself:latest
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ProveYourself'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_36510cf835b34ba28380b0bf9f823974 }}
        images: 'provendbdev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_426dc373dde84225af931a2ced427bff }}/proveyourself:${{ github.sha }}'